#!/usr/bin/env python

import sys
assert sys.argv[1:],'Arguments must be OBJECT.Property'
args = sys.argv[1:]
obj,prop = (args[0],args[1]) if len(args)==2 else args[0].split('.')

import PyTango
db = PyTango.Database()
if '/' in obj:
  value = db.get_device_property(obj,[prop])[prop]
else:
  value = db.get_property(obj,[prop])[prop]
  if not value:
    value = db.get_class_property(obj,[prop])[prop]

if not value:
  sys.exit(1)
else:
  print('\n'.join(value))

sys.exit(0)
  