/*
 *  
 *   File          :   StringImagePanel.java
 *  
 *   Project       :   atkpanel generic java application
 *  
 *   Description   :   The panel to display a  String image attribute
 *  
 *   Author        :   Faranguiss Poncet
 *  
 *   Original      :   May 2007
 *  
 *   $Revision$				$Author$
 *   $Date$					$State$
 *  
 *   $Log$
 *   Revision 3.5  2008/05/26 17:00:47  poncet
 *   The "Scalar" Tab is not refreshed anymore when it's hidden by another Tab. The attributePolledList refreshers (for trends) are not started any more by default.
 *
 *   Revision 3.4  2008/05/16 09:37:51  poncet
 *   Added clearModel() methods in all panel classes. Added clearAllModels() method in MainPanel.
 *
 *   Revision 3.3  2007/11/20 17:48:14  poncet
 *   Suppressed the Status and State attributes from scalar attribute lists because now they are added when attribute factory get + wildcard is called. This was not the case before ATK release 3.0.8.
 *
 *   Revision 3.2  2007/10/08 11:08:41  poncet
 *   Simplified the panel container hierarchy in ImagePanel.java to fix a display problem which was flashing in some cases. NumberImageViewer is now directly inside the ScrollPane.
 *
 *   Revision 3.1  2007/07/17 13:02:49  poncet
 *   For the spectrum and image attributes, now only the visible tab is refreshed to improve performance and network trafic.
 *
 *   Revision 3.0  2007/06/01 13:53:41  poncet
 *   Stop supporting Java 4.
 *
 *   Revision 2.18  2007/05/29 14:07:49  poncet
 *   Added the doFileQuit() method to the MainPanel class.
 *
 *   Revision 2.17  2007/05/23 13:42:53  poncet
 *   Added a public method : setExpertView(boolean) to the MainPanel class.
 *
 *   Revision 2.16  2007/05/03 16:46:21  poncet
 *   Added support for StringImage attributes. Needs ATK 2.8.11 or higher.
 *
 *   Revision 1.1  2007/05/03 16:39:42  poncet
 *   First release of StringImagePanel in cvs.
 *
 *  
 *   Copyright (c) 2007 by European Synchrotron Radiation Facility,
 *  		       Grenoble, France
 *  
 *                         All Rights Reserved
 *  
 *  
 */

package atkpanel;

/**
 *
 * @author  poncet
 */
import java.util.*;
import java.lang.*;
import javax.swing.*;
import javax.swing.event.*;
import java.awt.event.*;
import fr.esrf.tangoatk.core.*;
import fr.esrf.tangoatk.widget.attribute.*;

public class StringImagePanel extends javax.swing.JPanel
{

    private JScrollPane                  jScrollPane;
    private JPanel                       jPanel;
    private StringImageTableViewer       sitv;
    private IStringImage                 siModel;


    /** Creates new form StringImagePanel */
    public StringImagePanel()
    {
        siModel = null;
	initComponents();
    }

    /** Creates new form StringImagePanel to display a StringImage attribute */
    public StringImagePanel(IStringImage  niAtt)
    {
        initComponents();
	siModel = niAtt;
        sitv.setAttModel(niAtt);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()
    {
            java.awt.GridBagConstraints       gbc;
	    
	    
            gbc = new java.awt.GridBagConstraints();
            jScrollPane = new javax.swing.JScrollPane();
            jPanel = new javax.swing.JPanel();
            sitv = new StringImageTableViewer();
            
            
            setLayout(new java.awt.GridBagLayout());

            gbc.gridx = 0;
            gbc.gridy = 0;
            gbc.fill = java.awt.GridBagConstraints.BOTH;
            gbc.insets = new java.awt.Insets(3, 3, 3, 5);
            gbc.weightx = 1.0;
            gbc.weighty = 1.0;
            add(jScrollPane, gbc);
        
            
            jPanel.setLayout(new java.awt.GridBagLayout());
            
            gbc.gridx = 0;
            gbc.gridy = 0;
            gbc.fill = java.awt.GridBagConstraints.BOTH;
            gbc.weightx = 1.0;
            gbc.weighty = 1.0;
            jPanel.add(sitv, gbc);
            
            jScrollPane.setViewportView(jPanel);
        
    }
    
    protected IStringImage getModel()
    {
       return siModel;
    }

    
    protected void clearModel()
    {
       if (siModel == null) return;
       if (sitv == null) return;
       sitv.clearModel();
    }

}
